#!/bin/sh

# Default flags for various commands
alias ls='ls -p'
alias l='ls'
alias la='ll -A'
alias ps='ps auxf'
alias sshx='ssh -X'
alias df='df -h'
alias .='pwd'
alias ..='cd ..;pwd'
alias cd..='cd ..;pwd'
alias regrep='grep -r . -e'
alias findgrep='find . | grep'
alias chrome='google-chrome'

# Git aliases
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -a -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdcf="gdc | grep '^---'"
alias gr='git checkout' # r for Reset
alias gnh='git ls-files . --exclude-standard --others'
alias gl='git log --follow'
alias gsr='git svn rebase'
alias gsd='git svn dcommit'

# Simplified ssh commands
alias sshLocus='ssh -p 2242 locus.local'
alias sshxLocus='sshx -p 2242 locus.local'
alias sshHome='ssh -p 2242 dunmatt.com'
alias sshxHome='sshx -p 2242 dunmatt.com'
