#!/bin/sh

# Default flags for various commands
alias ls='ls -p --group-directories-first'
alias l='ls'
alias la='ll -A'
alias ps='ps auxf'
alias .='pwd'
alias ..='cd ..'
alias cd..='cd ..'

# Git aliases
alias gaa='git add -A'
alias gca='git commit -a'
alias gd='git diff'
alias gdc='git diff --cached'

