#!/bin/sh

# Default flags for various commands
alias ls='ls -p'
alias l='ls'
alias la='ll -A'
alias ps='ps auxf'
alias sshx='ssh -X'
alias .='pwd'
alias ..='cd ..'
alias cd..='cd ..'
alias regrep='grep -r . -e'

# Git aliases
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -a -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gr='git checkout' # r for Reset
alias gnh='git ls-files . --exclude-standard --others'
alias gl='git log --follow'
alias gsr='git svn rebase'
alias gsd='git svn dcommit'

# Simplified ssh commands
alias ssh-locus='ssh -p 2242 locus.local'
alias sshx-locus='sshx -p 2242 locus.local'
alias ssh-home='ssh -p 2242 dunmatt.com'
alias sshx-home='sshx -p 2242 dunmatt.com'
